### ISSUE TITLE
500 on non-product Amazon URLs

### ISSUE THREAD

**Issue by SelTheNardo** [atmafox/urlmaid#2]
Getting a 500 back for certain Amazon links. It seems browsing amazon's website in Incognito gives a whole bunch of non-normal product links, here's a few examples. I haven't done too much testing about which parts can be removed. I suspect these query parameters could show up in different orders as well.

Interestingly, with the deal link, if I remove all of the query parameters, only two products show up. If I leave them, more products show up. The tidier might have to parse the URL and reconstruct it with the minimum needed parameters instead of a regex wipe. Hard to say?

Deals: `https://www.amazon.com/deal/8e4e81a3/?_encoding=UTF8&showVariations=true&_ref=dlx_gate_sd_dcl_tlt_8e4e81a3_dt&pd_rd_w=IDoV8&content-id=amzn1.sym.00000000-0000-0000-0000-000000000000&pf_rd_p=00000000-0000-0000-0000-000000000000&pf_rd_r=6JGAAKNB7XAKZ8QH16AE&pd_rd_wg=6TPwu&pd_rd_r=00000000-0000-0000-0000-000000000000&ref_=pd_gw_unk`

Whatever this is: `https://www.amazon.com/s?bbn=1266092011&rh=n%3A1266092011%2Cp_n_deal_type%3A23566065011&pd_rd_r=00000000-0000-0000-0000-000000000000&pd_rd_w=4cnu0&pd_rd_wg=PN9nP&pf_rd_p=00000000-0000-0000-0000-000000000000&pf_rd_r=2FMW7JZJK9NJVC2GT9K1&qid=1677022046&rnid=23566063011&ref=pd_gw_unk`

And this: `https://www.amazon.com/b?node=23597934011&pf_rd_r=2FMW7JZJK9NJVC2GT9K1&pf_rd_p=00000000-0000-0000-0000-000000000000&pd_rd_r=00000000-0000-0000-0000-000000000000&pd_rd_w=ce3td&pd_rd_wg=PN9nP&ref_=pd_gw_unk`

Seasonal gift event I think?: `https://www.amazon.com/gcx/Easter-Toys-&-Games/gfhz/events/?categoryId=easter-toys&pd_rd_r=00000000-0000-0000-0000-000000000000&pd_rd_w=J921W&pd_rd_wg=PN9nP&pf_rd_p=00000000-0000-0000-0000-000000000000&pf_rd_r=2FMW7JZJK9NJVC2GT9K1&ref_=pd_gw_unk&scrollState=eyJpdGVtSW5kZXgiOjAsInNjcm9sbE9mZnNldCI6MTA1NS45NjY2NzQ4MDQ2ODc1fQ%3D%3D&sectionManagerState=eyJzZWN0aW9uVHlwZUVuZEluZGV4Ijp7ImFtYWJvdCI6MH19`

**Comment by atmafox** [comment]
This can also happen when a URL doesn't contain the appropriate search string.  This was likely a copy-paste error, as later attempts worked so the string to tidy that was actually used is lost to time.

In short: Other than fixing these and hardening the tidying process, I need to write tests to catch these kind of things.

**Comment by atmafox** [comment]
Well, crud.  `gcx` you can't just remove all of the query string like the `deal` and `dp` so I'll need to figure out what the magic query is.

`/s` is search and is likewise going to be difficult to tidy.  `/b` I can't even figure out what it is, but I did find this als which is easily tidyable:

`https://www.amazon.com/discover/bn/sofas-couches?ref=sbl_mm_bn_sc`

Going to keep investigating `/s` and `/b` too, see if I can't figure out what query is the magic one.
